services:
  app:
    build: .
    container_name: express-ts-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    env_file:
      - .env
    command: npm run dev

  db:
    image: postgres:16
    container_name: postgres-db
    restart: always
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: